- name: Include variable file
  include_vars:
    dir: ../../../global-vars
  tags:
    - basic_conf
    - include-vars

- name: Include user related tasks
  include_tasks: user.yml
  tags:
    - basic_conf
    - user

- name: Include other tasks
  include_tasks: other.yml
  tags:
    - basic_conf
    - other
