- name: Include variable file
  include_vars: 
    dir: ../../../global-vars
  tags:
    - pve
    - include-vars

# Install Proxmox VE on Debian 11 Bullseye

- name: Save IP to var
  environment:
    INTERFACE: "{{ pve_net_interface }}"
  shell: |
    ip -o -4 addr list $INTERFACE | awk '{print $4}' | cut -d/ -f1
  register: pve_ip
  tags:
    - pve
    - pve_install

- name: Save IP with CIDR to var
  environment:
    INTERFACE: "{{ pve_net_interface }}"
  shell: |
    ip -4 addr show $INTERFACE | awk '/inet/ {print $2}'
  register: pve_ip_cidr
  tags:
    - pve
    - pve_install

- name: Add static IP
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "{{ pve_ip.stdout }}       {{ pve_hostname }}.{{ pve_domain }}    {{ pve_hostname }}"
  tags:
    - pve_install

- name: Remove Debian DVD from repo list
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb cdrom'
    state: absent
  tags:
    - pve
    - pve_install

- name: Add Proxmox repository key
  shell: |
    wget https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
  tags:
    - pve
    - pve_install

- name: Add Proxmox repository
  apt_repository:
    repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
    filename: pve_install-repo
  tags:
    - pve
    - pve_install

- name: Update repos and do a full system upgrade
  apt:
    update_cache: true
    name: "*"
    state: latest
    autoremove: yes
  tags:
    - pve
    - pve_install

- name: Set Postfix server configuration type to 'local only'
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "'Local only'"
    vtype: string
  tags:
    - pve
    - pve_install

- name: Set Postfix mail name
  debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ pve_hostname }}.{{ pve_domain }}"
    vtype: string
  tags:
    - pve
    - pve_install

- name: Install PVE and other useful packages
  apt:
    update_cache: true
    name:
      # PVE packages
      - proxmox-ve
      - postfix
      - open-iscsi
      # General packages
      - curl
      - nfs-common
      - cifs-utils
      - htop
      - vim
      - neofetch
      - sudo
    state: latest
  tags:
    - pve
    - pve_install

- name: Reboot system
  reboot:
  tags:
    - pve
    - pve_install

- name: Remove Debian 11 kernel
  shell: |
    apt remove -y linux-image-amd64 'linux-image-5.10*'
    apt remove -y os-prober
    update-grub
  tags:
    - pve
    - pve_install

- name: Add vmbr0 interface
  blockinfile:
    path: /etc/network/interfaces
    insertafter: EOF
    block: |
      auto vmbr0
      iface vmbr0 inet static
        address {{ pve_ip_cidr.stdout }}
        gateway {{ gateway }}
        bridge-ports {{ pve_net_interface }}
        bridge-stp off
        bridge-fd 0
  tags:
    - pve
    - pve_install

## REMOVE THIS IF YOU HAVE A VALID SUBSCRIPTION
- name: Remove enterprise repository
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
  tags:
    - pve
    - pve_install

- name: Update repos
  apt:
    update_cache: true
  tags:
    - pve
    - pve_install
##

- name: Initialize Proxmox cluster
  environment:
    NAME: "{{ pve_cluster_name }}"
  shell: pvecm create $NAME
  ignore_errors: true
  tags:
    - pve
    - pve_install

- name: Reboot system
  reboot:
  tags:
    - pve
    - pve_install
