- name: Set storage variable
  set_fact:
    new_storage_ip: "{{ groups['new_storage'].0 | default(omit) }}"
  when: groups['new_storage'].0 is defined
  tags:
    - endpoint
    - wireguard

- name: Create wireguard container using docker-compose
  environment:
    PEER_NAMES: "{{ wireguard_peers }}"
    STORAGE_IP: "{{ groups['storage'].0 | default(new_storage_ip)}}"
  shell: |
    mkdir -p /opt/docker-compose/wireguard
    cd /opt/docker-compose/wireguard
    docker compose down
    docker volume rm wireguard_config
    cat << EOF | sudo tee docker-compose.yml > /dev/null
    version: "3"

    volumes:
      config:
        driver: local
        driver_opts:
          type: nfs
          o: "addr=${STORAGE_IP},rw,nfsvers=4,nolock,soft"
          device: ":/opt/nfs/endpoint/wireguard-config"

    services:
      wireguard:
        container_name: wireguard
        image: lscr.io/linuxserver/wireguard
        cap_add:
          - NET_ADMIN
          - SYS_MODULE
        environment:
          PUID: 1000
          PGID: 1000
          TZ: Europe/Zagreb
          SERVERURL: wg.grghomelab.me
          SERVERPORT: 51820
          PEERS: $PEER_NAMES
          PEERDNS: 192.168.100.1
          INTERNAL_SUBNET: 10.200.200.0
          LOG_CONFS: true
        volumes:
          - config:/config
          - /lib/modules:/lib/modules
        ports:
          - 51820:51820/udp
        sysctls:
          - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
    EOF
    docker compose up -d
  tags:
    - endpoint
    - wireguard

- name: Create scripts directory
  file:
    path: /root/scripts
    state: directory
    mode: 700
  tags:
    - endpoint
    - wireguard

- name: Add script for looking up info about peers
  template:
    src: wg-peer-info.sh.j2
    dest: /root/scripts/wg-peer-info.sh
    mode: 700
  tags:
    - endpoint
    - wireguard