# In practise this file is encrypted with Ansible Vault

# User variables
users:
  - username: user
    password: 'password'
    append: yes
    groups: [ sudo ]
    hosts:
      - 'all'
  - username: root
    password: 'password'
    append: yes
    hosts:
      - 'all'

vm_authorized_keys:
  - username: user
    keys:
      - 'ssh key'

pve_authorized_keys:
  - username: root
    keys:
      - 'ssh key'
  - username: user
    keys:
      - 'ssh key'

# Cluster variables
k3s_token: OTVlYmJkMmNjMmE3NzI1Y2Y4NTRkNDH5
