apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: oc
  namespace: oc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: oc
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 20