- name: Get kubectl config
  slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_config_base64
  when: cluster_init == 1
  tags:
    - control_plane
    - kubeconfig

- name: Decode config and store it in a variable
  set_fact:
    k3s_config: "{{ k3s_config_base64['content'] | b64decode }}"
  when: cluster_init == 1
  tags:
    - control_plane
    - kubeconfig

- name: Write kubectl config
  copy:
    content: "{{ k3s_config }}"
    dest: $HOME/.kube/config
  delegate_to: localhost
  become: false
  when: cluster_init == 1
  tags:
    - control_plane
    - kubeconfig

- name: Change kubectl endpoint address
  lineinfile:
    path: $HOME/.kube/config
    regex: "server: https://"
    line: "    server: https://{{ groups['endpoint'].0 | default(new_endpoint_ip) }}:6443"
  delegate_to: localhost
  become: false
  when: cluster_init == 1
  tags:
    - control_plane
    - kubeconfig