- name: Check if there are previous / faulty K3s installations
  shell: |
    systemctl status k3s-agent > /dev/null
    if [[ $? = 0 ]]; then
      echo no
    else
      echo yes
    fi
  args:
    executable: /bin/bash
  register: k3s_check_tmp
  tags:
    - worker
    - cleanup

- name: Set k3s_check variable
  set_fact:
    k3s_check: "{{ k3s_check_tmp['stdout'] }}"
  tags:
    - worker
    - cleanup

- name: Delete faulty K3s worker
  environment:
    NAME: "{{ worker_hostname }}"
  shell: bash ../roles/worker/files/delete-node.sh $NAME
  delegate_to: localhost
  become: false
  ignore_errors: true
  when: k3s_check is true or hostvars[groups['control_plane'].0 | default(groups['new_control_plane'].0)]['cluster_cleanup'] is defined
  tags:
    - worker
    - cleanup

- name: Remove previous K3s installations
  shell: |
    if [[ -f /usr/local/bin/k3s-agent-uninstall.sh ]]; then
      /usr/local/bin/k3s-agent-uninstall.sh
    fi
    sleep 5
  args:
    executable: /bin/bash
  when: k3s_check is true or hostvars[groups['control_plane'].0 | default(groups['new_control_plane'].0)]['cluster_cleanup'] is defined or agent_cleanup is defined
  tags:
    - worker
    - cleanup